name: Build exercises test

on:
  schedule:
    - cron: "0 6 * * *" 
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-in-docker:
    runs-on: ubuntu-latest  
    strategy:
      fail-fast: false
      matrix:
        course: [ncs-fund, ncs-inter, bt-fund, cell-fund, wifi-fund]
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v3.0.0
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout repository with example application
        uses: actions/checkout@v4
        with:
          path: test

      - name: Prepare west project
        run: |
          west init -l test/dev_academy
          cd test
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: dev_academy/nrf/samples/devacademy/${{ matrix.course }}/l9
        run: |
          west twister -T . -v --inline-logs --integration
          junit2html twister-out/twister.xml ${{ matrix.course }}_report.html

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test results ${{ matrix.course }}
          path: |
            dev_academy/nrf/samples/devacademy/${{ matrix.course }}/l9/twister-out/*.xml
            dev_academy/nrf/samples/devacademy/${{ matrix.course }}/l9/twister-out/*.json
            dev_academy/nrf/samples/devacademy/${{ matrix.course }}/l9/twister-out/*.log
